-- ============================================================================
-- Short QR links: stores.slug
--
-- The guest URL carried a 36-character UUID, which is most of an 82-character
-- link and a 37x37 QR code. A six-character slug on a short host
-- (qr.miraireach.ae/x7kp2m) is a 25x25 code that scans smaller and further,
-- and shows the guest a local domain instead of ".marketing".
--
-- Alphabet: 31 characters with no 0/o, 1/i/l ambiguity, so a slug read off a
-- printed card by eye is never mistyped. 31^6 = 887 million combinations;
-- gen_store_slug() still checks for a collision before returning.
--
-- The old /store/<uuid> URL keeps working forever: printed cards are never
-- invalidated. Safe to re-run.
-- ============================================================================

create extension if not exists pgcrypto;

create or replace function public.gen_store_slug()
returns text
language plpgsql
volatile
as $$
declare
  alphabet constant text := '23456789abcdefghjkmnpqrstuvwxyz';
  b bytea;
  s text;
  i int;
begin
  loop
    b := gen_random_bytes(6);
    s := '';
    for i in 0..5 loop
      s := s || substr(alphabet, (get_byte(b, i) % 31) + 1, 1);
    end loop;
    exit when not exists (select 1 from public.stores where slug = s);
  end loop;
  return s;
end;
$$;

alter table public.stores add column if not exists slug text;

update public.stores set slug = public.gen_store_slug() where slug is null;

alter table public.stores alter column slug set default public.gen_store_slug();
alter table public.stores alter column slug set not null;

create unique index if not exists stores_slug_key on public.stores (slug);

comment on column public.stores.slug is
  'Six-character code for the short guest link (https://<NEXT_PUBLIC_QR_HOST>/<slug>). Generated by gen_store_slug(); never changes once printed.';

-- Anon-safe view: append slug at the END (CREATE OR REPLACE only appends).
create or replace view public.public_store_review as
  select
    id,
    store_name,
    greeting_text,
    keywords,
    forced_keywords,
    google_review_url,
    brand_color,
    default_language,
    (is_active and (subscription_expires_at is null or subscription_expires_at > now())) as is_active,
    logo_url,
    business_category,
    entity_area,
    entity_city,
    entity_category_label,
    contact_channel,
    contact_dial_code,
    keyword_types,
    ai_review_enabled,
    slug
  from public.stores;

revoke all on public.public_store_review from anon, authenticated;
grant select on public.public_store_review to anon, authenticated;

-- Verification:
--   select slug from public.stores limit 5;                 -- six lowercase characters each
--   select count(*) from public.stores where slug is null;  -- 0
--   select slug from public.public_store_review limit 1;    -- visible to the QR page
